Fix quiz issue
SaranDharshanSP/TN-Tourism.github.io pull request #13
Opened 2024-12-25 07:30 UTC by Kavinesh11

When the form is submitted with incorrect answers, the error message "You have so much to discover about Tamil Nadu" is appended multiple times instead of appearing just once.

2024-12-25 07:31 UTC, Kavinesh11 commented
The PR is done @SaranDharshanSP anna , all sorted

2024-12-25 09:23 UTC, SaranDharshanSP requested changes
Could you deploy your branch and share the link ?
i will look into it

2024-12-26 04:22 UTC, Kavinesh11 commented
https://fix-quiz.netlify.app/  
check this out @SaranDharshanSP anna

2024-12-28 01:46 UTC, SaranDharshanSP approved these changes

2024-12-28 01:47 UTC, SaranDharshanSP commented
To merge it , it has some conflicts . Please have a look into it.

2025-01-01 05:33 UTC, SaranDharshanSP commented
To merge it , it has some conflicts . Please have a look into it. @Kavinesh11

2025-01-04 10:31 UTC, closed without merging